# Generated by Django 5.1 on 2024-08-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_readinglist_book_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinglist',
            old_name='book_uuid',
            new_name='book_id',
        ),
    ]
